### ISSUE TITLE
Missing libraries and argparse arguments

### ISSUE THREAD

**Issue by FabricioArendTorres** [vLAR-group/NVFi#1]
Hi,

I'm trying to run the code as instructed, but stumbled upon a few issues.

1. Some requirements are missing.
in `tensorf_model_utils.py` there are the following imports which are not in the requirements:
```
import plyfile
import skimage.measure
```
A pip install of plyfile and scikit-image seems to fix it, so I guess it should be added to the `requirements.txt`.

2. in `train_nvfi.py` the argument `config_args.keyframe` is missing, causing an attribute error. 
I assume this would be a boolean flag, indicating whether the keyframe optimization in section 3.2 of your paper is used..?

**Comment by Jinxi-Li** [comment]
Hi, 

Thanks for your interest and your great suggestions. Sorry that these bugs are all due to redundant codes, which were ignored to be deleted accidentally. Now I have fix a version. 

Btw, the `config_arg.keyframe` is used to control keyframe training only, which is not useful so I delete it. What you need is `static_dynamic` mode, representing joint optimization. 

Best, 
Jinxi
