### ISSUE TITLE
Questions about the construction of get_vel_loss()

### ISSUE THREAD

**Issue by JerryPW** [vLAR-group/NVFi#2]
Hi! Thanks for your great job and finally it opened! 
However, as I was reading the code of velocity part, I found that new random points and time were considered when calculating the velocity constrain. Is any reason to do so? Since usually I think the pts to render color should be the same with the pts calculating all the losses, and your code seems to be an exception. 

Looking forward to your reply soon!

**Comment by Jinxi-Li** [comment]
Hi! Firstly thanks for your interest in our project, hope it can help you. 

Our velocity constraint is optimized in a general PINN framework. Since we hope the velocity is conserved for all the possibly relevant points, we sample in the space and time (both observed and unobserved) uniformly, and select those might be occupied by the objects. In other words, the velocity constraint is a global constraint, so when you optimize local features (for rgb and density), you need to constrain other areas not sampled by your rendering points. 

There are some other examples sampling other points for more constraint. A particular one is to optimize an SDF via Eikonal loss as in [VolSDF](https://lioryariv.github.io/volsdf/). When they optimize local features, they sample more other points to constrain the whole field is a distance field. We share similar thoughts here. 

Hope my explain can solve your question. 

Best,
Jinxi

**Comment by JerryPW** [comment]
Thanks for reply!
Your answer is convincing!
